// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uarjeqtwlzvcxyzxwosl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcmplcXR3bHp2Y3h5enh3b3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Njc4NTMsImV4cCI6MjA1OTQ0Mzg1M30.c3WsefQcXE8lHxJMNvxjyKya4EGjGY_ddS4hyfE2bTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);